apiVersion: apps/v1
kind: Deployment
metadata:
  name: "humongous-healthcare-api"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "humongous-healthcare-api"
  template:
    metadata:
      labels:
        app: "humongous-healthcare-api"
    spec:
      containers:
      - name: "humongous-healthcare-api"
        image: "rgwinappacrt2.azurecr.io/humongous-healthcare-api:cc57b5a6a551f5cf62eab0553ba8dbe75be81ed6"
        env:
        - name: CosmosDb__Account
          valueFrom:
            secretKeyRef:
              name: cosmosdb
              key: cosmosdb-account
              optional: false
        - name: CosmosDb__Key
          valueFrom:
            secretKeyRef:
              name: cosmosdb
              key: cosmosdb-key
              optional: false
        - name: CosmosDb__DatabaseName
          value: HealthCheckDB
        - name: CosmosDb__ContainerName
          value: HealthCheck
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /HealthCheck
            port: http
        readinessProbe:
          httpGet:
            path: /HealthCheck
            port: http
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
